name: Akademia Albania | Edukim dhe Trainim Online ne Shqip
description: Akademia Shqiptare Online per trainim nepermjet internetit
meta_description: "Tutorial and Training in programming, internet, networking and other fields in Albanian"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: ""
domain_name: 'http://prod-hid.github.io/akd-al-web'
google_analytics: 'UA-63370434-2'
disqus: true
disqus_shortname: 'teodorrupiblog'

# Details for the RSS feed generator
url:            'http://teodorrupi.com/blog'
author:         'Teodor Rupi'
authorTwitter:  'teodorrupi'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
